name: Lint

on:
  push:
    branches: [main, dev]

  pull_request_target:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code

    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.9"
          cache: true

      - name: Install dependencies
        run: |
          pdm install -G :all
          echo `dirname $(pdm info --python)` >> $GITHUB_PATH

      - name: Lint with Ruff
        continue-on-error: true
        run: pdm lint --output-format github

      - name: Lint with Pyright
        uses: jakebailey/pyright-action@v2
        continue-on-error: true
        with:
          pylance-version: latest-release

  analyze:
    runs-on: ubuntu-latest
    name: CodeQL Analyze

    if: startsWith(github.ref, 'refs/heads/')

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Auto build
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
